WIP: Clarify matching rules
eclipse-ee4j/jaxrs-api pull request #972
Opened 2021-06-03 14:06 UTC by spericas

Clarify matching rules in the case where Content-Type and/or Accept headers are absent. Prompted by discussion in issue #970 and some potential ambiguity in implementations.

2021-06-03 21:06 UTC, andymc12 reviewed
Just a typo in the release notes page, but otherwise, LGTM.

2021-06-03 21:06 UTC, andymc12 commented on jaxrs-spec/src/main/asciidoc/chapters/appendix/_changes-since-3.0-release.adoc
> +* <<declaring_method_capabilities>>: Clarified resoure matching when `Content-Type`
```suggestion
* <<declaring_method_capabilities>>: Clarified resource matching when `Content-Type`
```

2021-06-04 13:56 UTC, andymc12 approved these changes
Looks good - thanks @spericas!

2021-06-08 15:53 UTC, chkal submitted a review, later dismissed
LGTM! Thanks!

2021-06-14 08:48 UTC, jansupol commented
I believe 
`If no Content-Type header is present in the request, the default media type is assumed to be application/octet-stream` clashes with [note 7](https://jakarta.ee/specifications/restful-ws/3.0/jakarta-restful-ws-spec-3.0.html#_footnotedef_7): (Section 3.7.2.3.b, describing C_M): `If any of these types or sets of types are unspecified, */* and {*/*} are assumed`.

2021-06-14 08:58 UTC, jansupol requested changes
-1 until the clash gets resolved. To me, this sounds like a backward incompatible change, not a clarification. This can be fixed in Algorithm 3.7.3, by making note 7 more clear (or someone can prove me being wrong), but excluding the Consumes (C_M) from note 7 is a backward incompatibility, which I am not sure should be brought in to a minor version of the Spec.

2021-06-14 09:04 UTC, jansupol commented
Please do not take me wrong, I agree with clarification, I am just pointing at the processing issues.

2021-06-14 13:48 UTC, andymc12 commented
@jansupol I think that is a good catch, but I think the conflict may have already been in the spec. In [section 4.2.1](https://jakarta.ee/specifications/restful-ws/3.0/jakarta-restful-ws-spec-3.0.html#message_body_reader), it states that:
> 1. Obtain the media type of the request. If the request does not contain a `Content-Type` header then use `application/octet-stream`.

It's likely a stretch, but it could be that note 7 is referring to the set of applicable methods.  In that case, I think everything is fine.  The rule has always been that if a resource class/method is not annotated with `@Consumes`, then it is expected that the resource method consumes `*/*`.  

So it would resolve something like this - say we have these resource methods:
```
@POST
@Consumes("application/octet-stream")
@Path("1")
Response consumesOctetStream(SomeObject obj) {...}

@POST
@Path("2")
Response noConsumes(SomeObject obj) {...}

@POST
@Consumes("application/xml")
@Path("3")
Response consumesXml(SomeObject obj) {...}
```

If I send a POST to `/1` with no `Content-Type` header, the runtime should match it to the `consumesOctetStream` method, and process the entity body as `application/octet-stream`.

Likewise, if I send POST to `/2` with no `Content-Type` header, the runtime should match it to the `noConsumes` method, and process the entity body as `application/octet-stream`. Unlike `/1`, this method will also be matched to requests with any value for the `Content-Type` header.

If I send a POST to `/3` with no `Content-Type` header, the runtime should respond with a `415` because the missing `Content-Type` header is assumed to be `application/octet-stream` which is incompatible with `application/xml`. 

Does that make sense?  If I'm misunderstanding it, then I think we probably do need more clarification.  Even so, it might be worth clarifying that Note 7 is referring the `M` - the set of methods, not the `Content-Type` or `Accept` headers.

2021-06-14 15:20 UTC, spericas commented
> -1 until the clash gets resolved. To me, this sounds like a backward incompatible change, not a clarification. This can be fixed in Algorithm 3.7.3, by making note 7 more clear (or someone can prove me being wrong), but excluding the Consumes (C_M) from note 7 is a backward incompatibility, which I am not sure should be brought in to a minor version of the Spec.

The footnote refers to the `@Consumes` and `@Produces` parts, which may be omitted and default to `*/*` as stated elsewhere (and in our API code). It doesn't make sense to talk about wildcards as possible values for `Content-Type`. Will update the footnote to make this clear.

2021-06-14 15:23 UTC, spericas commented
> @jansupol I think that is a good catch, but I think the conflict may have already been in the spec. In [section 4.2.1](https://jakarta.ee/specifications/restful-ws/3.0/jakarta-restful-ws-spec-3.0.html#message_body_reader), it states that:
> 
> > 1. Obtain the media type of the request. If the request does not contain a `Content-Type` header then use `application/octet-stream`.
> 
> It's likely a stretch, but it could be that note 7 is referring to the set of applicable methods. In that case, I think everything is fine. The rule has always been that if a resource class/method is not annotated with `@Consumes`, then it is expected that the resource method consumes `*/*`.

 Yes, see my comment. Section 4.2.1 should now align better with this new clarification that we are adding. Of course, this section is about MBR's not matching.

> 
> So it would resolve something like this - say we have these resource methods:
> 
> ```
> @POST
> @Consumes("application/octet-stream")
> @Path("1")
> Response consumesOctetStream(SomeObject obj) {...}
> 
> @POST
> @Path("2")
> Response noConsumes(SomeObject obj) {...}
> 
> @POST
> @Consumes("application/xml")
> @Path("3")
> Response consumesXml(SomeObject obj) {...}
> ```
> 
> If I send a POST to `/1` with no `Content-Type` header, the runtime should match it to the `consumesOctetStream` method, and process the entity body as `application/octet-stream`.

 Exactly.

> 
> Likewise, if I send POST to `/2` with no `Content-Type` header, the runtime should match it to the `noConsumes` method, and process the entity body as `application/octet-stream`. Unlike `/1`, this method will also be matched to requests with any value for the `Content-Type` header.
> 
> If I send a POST to `/3` with no `Content-Type` header, the runtime should respond with a `415` because the missing `Content-Type` header is assumed to be `application/octet-stream` which is incompatible with `application/xml`.
> 

 Right.

2021-06-14 15:32 UTC, jansupol commented
@andymc12 What you say makes perfect sense, but the note is better to be clarified, too, if it is to be understood as you say. Section 4.2.1 discusses the message body provider selection, and Note 7 refers to resource method matching, which is strictly speaking not the same task.

2021-06-14 15:45 UTC, spericas commented
> > -1 until the clash gets resolved. To me, this sounds like a backward incompatible change, not a clarification. This can be fixed in Algorithm 3.7.3, by making note 7 more clear (or someone can prove me being wrong), but excluding the Consumes (C_M) from note 7 is a backward incompatibility, which I am not sure should be brought in to a minor version of the Spec.
> 
> The footnote refers to the `@Consumes` and `@Produces` parts, which may be omitted and default to `*/*` as stated elsewhere (and in our API code). It doesn't make sense to talk about wildcards as possible values for `Content-Type`. Will update the footnote to make this clear.

Footnote has now been updated as well.

2021-06-14 16:27 UTC, andymc12 approved these changes
Changes lgtm.  Thanks!

2021-06-14 17:02 UTC, jansupol approved these changes
Thanks!

2021-06-18 21:34 UTC, mkarg approved these changes

2021-06-19 13:27 UTC, chkal approved these changes

2021-06-21 13:55 UTC, merged